/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Bookify-componentes/comp.libro`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Bookify-componentes/Encabezadobook`; params?: Router.UnknownInputParams; } | { pathname: `/../components/filter-buttons`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agregar` | `/agregar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Buscar` | `/Buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Inicio` | `/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Bookify-componentes/comp.libro`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Bookify-componentes/Encabezadobook`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/filter-buttons`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agregar` | `/agregar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Buscar` | `/Buscar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Inicio` | `/Inicio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../components/Bookify-componentes/comp.libro${`?${string}` | `#${string}` | ''}` | `/../components/Bookify-componentes/Encabezadobook${`?${string}` | `#${string}` | ''}` | `/../components/filter-buttons${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agregar${`?${string}` | `#${string}` | ''}` | `/agregar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Buscar${`?${string}` | `#${string}` | ''}` | `/Buscar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Inicio${`?${string}` | `#${string}` | ''}` | `/Inicio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Bookify-componentes/comp.libro`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Bookify-componentes/Encabezadobook`; params?: Router.UnknownInputParams; } | { pathname: `/../components/filter-buttons`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agregar` | `/agregar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Buscar` | `/Buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Inicio` | `/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
    }
  }
}
