/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agregar` | `/agregar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Buscar` | `/Buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Inicio` | `/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ubicacion` | `/ubicacion`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/libro/[id]` | `/libro/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agregar` | `/agregar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Buscar` | `/Buscar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Inicio` | `/Inicio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ubicacion` | `/ubicacion`; params?: Router.UnknownOutputParams; } | { pathname: `/Auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Auth/Register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/libro/[id]` | `/libro/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agregar${`?${string}` | `#${string}` | ''}` | `/agregar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Buscar${`?${string}` | `#${string}` | ''}` | `/Buscar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Inicio${`?${string}` | `#${string}` | ''}` | `/Inicio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ubicacion${`?${string}` | `#${string}` | ''}` | `/ubicacion${`?${string}` | `#${string}` | ''}` | `/Auth/Login${`?${string}` | `#${string}` | ''}` | `/Auth/Register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agregar` | `/agregar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Buscar` | `/Buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Inicio` | `/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ubicacion` | `/ubicacion`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/Register`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/libro/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/libro/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/libro/[id]` | `/libro/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
